global:
  scrape_interval: 5s

scrape_configs:
  - job_name: hydra_exporter
    static_configs:
      - targets: ["hydra-exporter:9100"]

  - job_name: hydra_service
    metrics_path: /metrics
    static_configs:
      - targets: ["hydra-service:8000"]
